### ISSUE TITLE
Feat: issue_1

### ISSUE THREAD

**Issue by junkue20** [jinuk0316/sns#5]
# 이슈제목
- 등록일 : 2023.07.12
- 등록자 : 박준규

## 📄 이슈 내용
- 현재 사용하려는 sns 서비스의 기획, 사용 기술 등을 간단하게 요약 및 정리

## 📄 상세 내용
- 프로젝트 타겟층 선정
- 사용 디바이스 선정

## ✅ 체크리스트
- [] 사용 핵심 기능 정리
- [] 웹 및 앱 UI 구현 (Figma)

**Comment by KittelLee** [comment]
부족한 내용 추가해주세요

**Comment by seacrab808** [comment]
이거 제목 수정하시고 라벨 붙여주세요 준규님.

**Comment by mysdpy30s** [comment]
제대로 작업 부탁드립니다.

**Comment by junkue20** [comment]
다들 죄송합니다 ㅠㅠ

**Comment by Sinary00** [comment]
체크리스트가 제대로 구현이 안되었습니다.
